# Generated by Django 5.0.2 on 2024-02-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_base_price', models.FloatField()),
                ('distance_additional_price', models.FloatField()),
                ('time_multiplier_factor', models.FloatField()),
                ('waiting_charges', models.FloatField()),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
