# Generated by Django 5.0.2 on 2024-02-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricingconfiguration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfiguration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricingconfiguration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pricingconfiguration',
            name='last_modified_at',
        ),
        migrations.RemoveField(
            model_name='pricingconfiguration',
            name='last_modified_by',
        ),
    ]
