# Generated by Django 5.0.2 on 2024-02-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_remove_pricingconfiguration_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatedPrice',
        ),
    ]
